export const STATUS_CODES = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500
};

export const DYNAMODB_TABLES = {
    PRODUCTS_TABLE: process.env.PRODUCTS_TABLE,
    STOCKS_TABLE: process.env.STOCKS_TABLE
}

export const DYNAMODB_TABLES_PRIMARY_KEY = {
    PRODUCTS_TABLE_PRIMARY: 'id',
    STOCKS_TABLE_PRIMARY: 'product_id'
}

export const ERROR_MESSAGE = {
    INTERNAL_SERVER_ERROR: 'Internal Server Error'
}